name: Documentation Dokka
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Gradle Dokka Task
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
          arguments: dokkaHtml

      - name: Deploy Dokka HTML
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dokka/html
          target-folder: dokka