name: Documentation Allure report
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Gradle Tests
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
          arguments: clean test

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.10
        working-directory: bingo
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

#      - name: Publish test report
#        uses: peaceiris/actions-gh-pages@v4
#        if: always()
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_branch: gh-pages
#          publish_dir: allure-history

      - name: Deploy Allure reports HTML
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: allure-history
          target-folder: bingo