name: Documentation Gradle Dependencies
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Gradle HTML dependencies Task
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
          arguments: htmlDependencyReport

      - name: Deploy Gradle Dependencies HTML
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/reports/project/dependencies
          target-folder: gradle-dependencies